---
# tasks file for /mnt/host/c/Users/Coren/TP1 DEVOPS/ansible/roles/database

 - name: Run the database container
  docker_container:
    name: my_postgres_container
    image: eldestructor/tp-devops-database
    state: started
    networks:
      - name: app-network
    env:
      POSTGRES_DB: db
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
