name: CI devops 2024

on:
  push:
    branches: 
      - main
      - develop 
  pull_request:

jobs:
  test-backend: 
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2.5.0
      - name: Set up JDK 17
        uses: actions/setup-java@v3  
        with:
          java-version: '17'
          distribution: 'adopt'      
      - name: Build and test with Maven
        run: |
          cd Java2/simpleapi/simple-api-student-main/simple-api-student-main
          mvn clean verify

  build-and-push-docker-image:
    needs: test-backend
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0
      - name: Build and push backend image
        uses: docker/build-push-action@v3
        with:
          context: ./Java2/simpleapi/simple-api-student-main/simple-api-student-main
          tags: ${{ secrets.eldestructor }}/tp-devops-simple-api:latest
      - name: Build and push database image
        uses: docker/build-push-action@v3
        with:
          context: ./postgres
          tags: ${{ secrets.eldestructor }}/tp-devops-database:latest
      - name: Build and push HTTP server image
        uses: docker/build-push-action@v3
        with:
          context: ./HTTP
          tags: ${{ secrets.eldestructor }}/tp-devops-httpd:latest

